### ISSUE TITLE
[Desktop] Switch screens by scrolling

### ISSUE THREAD

**Issue by 12people** [kumar-aakash86/flutter_overboard#11]
Switching screens in Overboard works perfectly on mobile, via a simple swipe left or right.
On laptops, however, the standard way to switch would be scrolling to switch, which Overboard doesn't support yet.

It would be great if one could switch screens by scrolling horizontally on laptops.

**Comment by kumar-aakash86** [comment]
This sounds like a great idea. I will work on it.
Thanks for the idea.

**Comment by 12people** [comment]
Amazing, thank you so much! And thanks for the fast response!

**Comment by kumar-aakash86** [comment]
@12people 
The support for the keyboard left/right keys & mouse scroll is added in the package. It needs a new parameter **allowScroll** which is by default false. 
Please try the new version 3.1.1 once its updated & let me know your thoughts on it.

Once you checked it & give your thumb up. I will close this issue.

**Comment by 12people** [comment]
Wow — you were much faster than expected! Thanks so much for taking the time to work on this!

The keyboard keys are an excellent touch — thanks for those!

As for the scroll, would it be possible to change to horizontal scrolling instead of (or perhaps in addition to) vertical scrolling? Most laptop trackpads allow easy scrolling in both directions and it feels counter-intuitive to scroll vertically when the onboarding itself is horizontal. What do you think?

Also, a minor bug: the transition animations always show the transition from the first slide, even if the user is switching between the third and fourth slide. Here's how it looks in my case: https://mega.nz/file/UZ5kjahb#CXq7O-hzupHNjIJ_E0cjT6lZxYY0WHQeSVci3tiB954

**Comment by kumar-aakash86** [comment]
Thanks for testing it. I haven't tried vertical scroll as I thought about mouse wheel. I will try to add both if possible. 
I think the screen 1 glitch is happening on web as never seen this in mobile before but I have to check again. I have to see  & understand the issue first to fix this one.

I want to ask you one thing though. Are you creating desktop or web app?

**Comment by kumar-aakash86** [comment]
Hi @12people 
I have added the required fixes in the code.  Horizontal touchpad swipe support is also added.
Can you please try to test it & let me know if its working?

Feel free to reopen the issue if you still find any issue.

**Comment by 12people** [comment]
For some reason, it's still not working quite well on a Mac, but that's okay — I decided to use a standard PageView to get natural scrolling on the desktop.

Either way, thanks for being so quick to respond and help!
