### ISSUE TITLE
Accept string for "skip", "next" and "finish" button.

### ISSUE THREAD

**Issue by Xentraxx** [kumar-aakash86/flutter_overboard#2]
It would be awesome to be able to define the text of the buttons in order to localize them.

**Comment by kumar-aakash86** [comment]
#3

**Comment by kumar-aakash86** [comment]
Commit d536f0cf318a917ab75034e92c5cbc204e96846c closes #2

**Comment by kumar-aakash86** [comment]
@Xentraxx 
Thanks for the suggestion. This feature is added & is available in the 1.1.5
[flutter_overboard](https://pub.dev/packages/flutter_overboard)

Commit d536f0cf318a917ab75034e92c5cbc204e96846c closes #2
